apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-cred
data:
  .dockerconfigjson: "ewoJImF1dGhzIjogewoJCSJyZWdpc3RyeS5naXRsYWIuaWNzLm11bmkuY3o6NDQzIjogewoJCQkiYXV0aCI6ICJNelUzTVRVMk9rNWFPRFppZUdGdVVsWkdVbmRvYXpSNFdHaFUiCgkJfQoJfQp9"
type: kubernetes.io/dockerconfigjson
